# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ffb544c0febafc2abaf07bec08aaad44"
name = "Inventory Copilot"
handle = "inventory-copilot-app"
application_url = "https://inventory-copilot-30862fa79df0.herokuapp.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled", "products/create", "products/update", "products/delete", "orders/create", "orders/delete", "orders/cancelled", "orders/fulfilled", "orders/paid", "orders/partially_fulfilled", "orders/updated" ]
  uri = "https://hkdk.events/i1tjfeqzic42c3"
  include_fields = [
    "id",
    "created_at",
    "updated_at",
  ]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,read_inventory"

[auth]
redirect_urls = [ "https://inventory-copilot-30862fa79df0.herokuapp.com/api/auth" ]
